Repository CirclesUBI/circles-myxogastria, pull requests merged in 2021-03, with the labels that each got.

#160 Allow generic user notifications
  .env.example
  locales/en.json
  src/components/AppNote.js
  webpack.config.babel.js
Labels: enhancement :sparkler:, priority ★★★, ux :waffle:

#162 Update README.md
  README.md
Labels: documentation :writing_hand:

#163 Link node version in .nvmrc with GH Actions
  .github/workflows/run-tests.yml
  .nvmrc
  README.md
Labels: CI :ice_skate:
